#faster

In [ ]:
# create a list of 1,000,000 salaries ranging from 50,000 to 100,000

In [ ]:
import random

random.randint(50000,100000)

56319

In [ ]:
salary_list = [random.randint(50000,100000) for _ in range(1000000)]       # _ it's for random value
salary_list

[69478,
 95067,
 97637,
 87624,
 67449,
 51627,
 71831,
 97349,
 50104,
 64592,
 81805,
 59445,
 80491,
 93830,
 56827,
 82641,
 66696,
 89057,
 78506,
 51408,
 99358,
 79049,
 52845,
 95224,
 91186,
 56242,
 94422,
 93679,
 99292,
 99178,
 87728,
 77898,
 51567,
 90499,
 89186,
 64624,
 75873,
 68367,
 59461,
 59549,
 84586,
 84592,
 84087,
 98877,
 82288,
 81893,
 55174,
 52134,
 55792,
 54817,
 99503,
 84422,
 82061,
 96198,
 74888,
 80934,
 78446,
 52255,
 70708,
 94846,
 75704,
 85108,
 74636,
 90272,
 51766,
 64174,
 94955,
 99791,
 57696,
 90468,
 50248,
 89273,
 59919,
 67723,
 94434,
 71133,
 67545,
 80880,
 52983,
 75075,
 68266,
 95772,
 80852,
 50622,
 86952,
 84867,
 94012,
 60596,
 66418,
 66134,
 89988,
 71098,
 62461,
 85474,
 50390,
 87656,
 52550,
 98467,
 63916,
 90870,
 64353,
 87095,
 76514,
 94392,
 52196,
 68136,
 50117,
 67607,
 71242,
 76554,
 52948,
 72491,
 70212,
 81312,
 94345,
 83637,
 76548,
 90199,
 82780,
 60191,
 58169,
 68424,
 69870,
 78269,
 67258,


In [ ]:
# let's find something analytical importance such as mean/ avg

In [ ]:
import statistics

statistics.mean(salary_list)

74995.362784

In [ ]:
# using magic command( %% )
# in %%timeit operation it'll run multiple time and provide us what is avg time took to run whole thing

In [ ]:
%%timeit

statistics.mean(salary_list)

241 ms ± 7.29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# let's do with numpy

In [ ]:
import numpy as np

In [ ]:
%%timeit
np.mean(salary_list)

55.8 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
# its 4 time faster, it'll help in large data set

#basic operations in numpy

In [ ]:
import numpy as np

In [ ]:
my_arrary = np.array([1,2,3,4])
my_arrary

array([1, 2, 3, 4])

In [ ]:
my_arrary.mean()

np.float64(2.5)

In [ ]:
# job totles
job_titles = np.array(['data analyst','data engineer','data scientist'])

# base salary
base_salary = np.array([50000,70000,100000])

# bonus rate
bonus_rate = np.array([0.9, 1.2, 5.3])

In [ ]:
total_salary_list = base_salary * (1 + bonus_rate)
total_salary_list

array([ 95000., 154000., 630000.])

In [ ]:
total_salary = total_salary_list.sum()
total_salary

np.float64(879000.0)

In [ ]:
np.mean(total_salary_list)

np.float64(293000.0)



---



---



In [ ]:
# if we have missing data and we put 0 value to missing data

In [ ]:
# job totles
job_titles = np.array(['data analyst','data engineer','data scientist','Ai engineer'])

# base salary
base_salary = np.array([50000,70000,100000,0])

# bonus rate
bonus_rate = np.array([0.9, 1.2, 5.3, 0])

In [ ]:
total_salary_list = base_salary * (1 + bonus_rate)
np.mean(total_salary_list)

np.float64(219750.0)

In [ ]:
# it'll drag down our mean value



---



---



In [ ]:
# let's try none instead of 0

In [ ]:
# job totles
job_titles = np.array(['data analyst','data engineer','data scientist','Ai engineer'])

# base salary
base_salary = np.array([50000,70000,100000,None])

# bonus rate
bonus_rate = np.array([0.9, 1.2, 5.3, None])

In [ ]:
total_salary_list = base_salary * (1 + bonus_rate)
total_salary_list

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'



---



---



In [ ]:
# numpy has nan value , it means 'not a number'
# it's specifically for numarical data

In [ ]:
# job totles
job_titles = np.array(['data analyst','data engineer','data scientist','Ai engineer'])

# base salary
base_salary = np.array([50000,70000,100000, np.nan])

# bonus rate
bonus_rate = np.array([0.9, 1.2, 5.3, np.nan ])

In [ ]:
total_salary_list = base_salary * (1 + bonus_rate)
total_salary_list

array([ 95000., 154000., 630000.,     nan])

In [ ]:
np.mean (total_salary_list)

np.float64(nan)

In [ ]:
np.nanmean (total_salary_list)

np.float64(293000.0)



---



---



In [ ]:
# Example: An array representing the number of years of experience required for three different data science job listings.
years_of_experience = np.array([1, 2, 3, 4, 5])

In [ ]:
years_of_experience_add = years_of_experience + 1
years_of_experience_add

array([2, 3, 4, 5, 6])

In [ ]:
years_of_experience - 1

array([0, 1, 2, 3, 4])

In [ ]:
years_of_experience[1:3]

array([2, 3])

In [ ]:
print(years_of_experience>2 )
print(years_of_experience[years_of_experience > 2])

[False False  True  True  True]
[3 4 5]





---


---



In [ ]:
# lets create a list with 10 yearly salaries for a Senior Data Analyst job

In [ ]:
import random

salary = [random.randint(100_000 , 150_000) for num in range (10)]
salary

[118781,
 108801,
 135178,
 149318,
 131168,
 115371,
 142725,
 111937,
 107864,
 107647]

In [ ]:
#Now we'll convert this list into a NumPy array.
salary_array = np.array(salary)
salary_array

array([118781, 108801, 135178, 149318, 131168, 115371, 142725, 111937,
       107864, 107647])

In [ ]:
np.sum(salary_array)

np.int64(1228790)

In [ ]:
#Calculate the product of the elements
np.prod(salary_array)

np.int64(3213471233417587712)

In [ ]:
# Calculates the cumulative sum of elements
np.cumsum(salary_array)

array([ 118781,  227582,  362760,  512078,  643246,  758617,  901342,
       1013279, 1121143, 1228790])

In [ ]:
# Calculates the cumulative product of elements
np.cumprod(salary_array)

array([              118781,          12923491581,     1746971744936418,
        2599909978482340300,    34366903131745408, -1105994634954131072,
       -4295235095724073088,   206627100184067968,  3958693213168948224,
        3213471233417587712])

In [ ]:
# Calculate the average salary
np.mean(salary_array)

np.float64(122879.0)

In [ ]:
# find the median salary
np.median(salary_array)

np.float64(117076.0)

In [ ]:
# calculate the variance
np.var(salary_array , ddof=1)   #ddof=1 for sample variance

np.float64(240155836.0)

In [ ]:
# Calculate the standard deviation
np.std(salary_array , ddof=1 )            ## ddof=1 for sample standard deviation

np.float64(15496.96215391907)

In [ ]:
salary_with_nan = np.array([123124, np.nan, 145000, 128000, 110000, 149999, np.nan, 135000, 115000, 140000], dtype=float)
salary_with_nan

array([123124.,     nan, 145000., 128000., 110000., 149999.,     nan,
       135000., 115000., 140000.])

In [ ]:
# If you want to replace existing values with np.nan, for example, if certain values are considered invalid or outliers:
salary_with_nan[salary_with_nan < 130_000] = np.nan
salary_with_nan

array([    nan,     nan, 145000.,     nan,     nan, 149999.,     nan,
       135000.,     nan, 140000.])

#where

In [ ]:
# np.where check elements of an array against a condition and to assign a value for True and another for false.
# Syntax: np.where(condition).
# It's commonly used to conditionally replace array elements.

In [ ]:
salary_array

array([118781, 108801, 135178, 149318, 131168, 115371, 142725, 111937,
       107864, 107647])

In [ ]:
np.where(salary_array < 120000 , 120000 , salary_array)

array([120000, 120000, 135178, 149318, 131168, 120000, 142725, 120000,
       120000, 120000])



---



---



In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
# it's like list. then why do we need np.array
# 1. less memory
# 2. fast
# 3. convinient

In [ ]:
import time

size = 1000000

In [ ]:
# python list
l1 = range(size)
l2 = range(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time()-start)*1000)

python list took:  18.57137680053711


In [ ]:
# numpy array
a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = a1 + a2
print("numpy took: ", (time.time()-start)*1000)

numpy took:  0.6043910980224609


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(b - a)
print(a * b)
print(b / a)


[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]


In [ ]:
a = np.array([1,2,3])
a.ndim

1

In [ ]:
# let's create 2 dimentional array
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [ ]:
a.itemsize     # it'll print the bite size each elements

8

In [ ]:
a.dtype

dtype('int64')

In [ ]:
# let's initialuze same array with a different data type
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a.itemsize

8

In [ ]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [ ]:
print(a.size)       # total number of elements
print(a.shape)      # rows , column

6
(3, 2)


In [ ]:
# initialize arrays with some placeholder numbers (eg; zero)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# let's creat a range
np.arange(1,5)      # array range

array([1, 2, 3, 4])

In [ ]:
np.arange(1,9,3)

array([1, 4, 7])

In [ ]:
# let's creat linearly spaced
np.linspace(1,5,10)       # it's creat 10 numbers between 1-5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
# reshape
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print()
print(a.shape)
print()
print(a.reshape(2,3))
print()
print(a.reshape(6,1))

[[1 2]
 [3 4]
 [5 6]]

(3, 2)

[[1 2 3]
 [4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
# ravel function will flattern our array
a.ravel()    # it'll not touch original array

array([1, 2, 3, 4, 5, 6])

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis=0))       # axis = 0 means it'll sum column
print(a.sum(axis=1))       # axis = 1 means it'll sum row by rows

1
6
21
[ 9 12]
[ 3  7 11]


In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [ ]:
np.std(a)

np.float64(1.707825127659933)

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a)
print()
print(b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [ ]:
a + b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a * b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# let's do matrix product
a.dot(b)   # it's do a matrix products of these 2 individual matrices

array([[19, 22],
       [43, 50]])

# slicing

In [ ]:
a = np.array([5,6,7])

In [ ]:
a[0:2]

array([5, 6])

In [ ]:
a[-1]

np.int64(7)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[1,2]    # in 1st row 2nd column  * index start with 0

np.int64(6)

In [ ]:
a[0,2]

np.int64(3)

In [ ]:
a[0:2,2]          # 1st and 2nd rowns 2nd column

array([3, 6])

In [ ]:
a[1:4,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
a[-1]

array([7, 8, 9])

In [ ]:
a[:,1:3]     # in here ":" it'll include all column

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
for rows in a:
  print(rows)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
for rows in a:
  for cell in rows:
    print(cell)

1
2
3
4
5
6
7
8
9


In [ ]:
# flattern the array ( another way)
for rows in a.flat:
  print(rows)

1
2
3
4
5
6
7
8
9


In [ ]:
# 3rd way
for x in np.nditer(a, order= 'C'):    # "c" order go by rows to row, "fortran" order goes by column to column
  print(x)

1
2
3
4
5
6
7
8
9


In [ ]:
for x in np.nditer(a, order= 'F'):
  print(x)

1
4
7
2
5
8
3
6
9


In [ ]:
for x in np.nditer(a, order= 'F', flags=['external_loop']):
  print(x)

[1 4 7]
[2 5 8]
[3 6 9]


In [ ]:
# check np.nditer module

# stacking

In [ ]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)
print(a)
print()
print(b)

[[0 1]
 [2 3]
 [4 5]]

[[ 6  7]
 [ 8  9]
 [10 11]]


In [ ]:
# vertically stack them together
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

# split

In [ ]:
a = np.arange(30).reshape(2,15)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [ ]:
a = np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [ ]:
# to get specific array
a[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# indexing with booling array

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[b]         # it looked at b array and wherever it found true it return those elements

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

# itrate through 2 numpy array simultaneously

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(3,15,4).reshape(3,1)
print(a)
print()
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 3]
 [ 7]
 [11]]


In [ ]:
for x,y in np.nditer([a,b]):
  print(x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11
